### ISSUE TITLE
Suggestion to switch to std::lgamma everywhere

### ISSUE THREAD

**Issue by Shians** [catavallejos/BASiCS#61] opened 2018-10-18 04:16 UTC
So with some very crude profiling I see that most of the time in `BASiCS_MCMC()` is spent running `R::lgammafn()` for the log-likelihood. With some crude benchmarking I find that using `std::lgamma` can speed this up by 30+%.

I would suggest you switch the remaining [`R::gammafn()`](https://github.com/catavallejos/BASiCS/search?q=lgammafn&unscoped_q=lgammafn) to `std::lgamma` from `#include<cmath>` and get some free performance.

**Comment by catavallejos** [comment] 2018-10-18 08:01
Thanks @Shians for the suggestion. I will try this and let you know how it goes.

Best,

Catalina

**Comment by catavallejos** [comment] 2018-10-18 08:39
Done!! Your suggestion works wonderfully!! Thank you so much @Shians !

**Comment by catavallejos** [comment] 2018-10-19 19:35
Hi @Shians,

As I mentioned above, I tried your suggestion and we good a very good speed-up on our code. However, while everything works well on my computers (Mac OS), there is an error in the Bioconductor build report for linux and Windows:

```
error: 'lgamma' is not a member of 'std'
```

Have you encountered an issue like this before? As the new Bioconductor release is fast approaching, I will temporarily return to the old version (calling `R::lgammafn()`), but I would be great to sort this out.

Thanks!

Cata

**Comment by Shians** [comment] 2018-10-19 21:18
Bit strange since you already use `std::lgamma` [here](https://github.com/catavallejos/BASiCS/blob/d7c22a2861812e59a8a8ecb959be6e0987ed0106/src/general_utils.cpp#L377). I'm guessing it's because `std::lgamma` is technically a C++11 and above feature, though some compilers implemented it ahead of standard, so you end up with it working some places but not others.

If this is the case all you need to do is add a [C++11 requirement](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Using-C_002b_002b11-code) to your Makevars, so

```
CXX_STD = CXX11
```

Somewhere near the top of your src/Makevars and src/Makevars.win files. This will make it hard for people who haven't updated their C++ compilers in 10 years to use your software but I hope that's an acceptable loss.

**Comment by catavallejos** [comment] 2018-10-19 22:19
Thanks for the quick reply! Indeed, it looks like the issue is the use of C++11. I will add that as a requirement for `BASiCS` (we shouldn't loose users, because our dependency to `scran` implies that C++11 is already a requirement for us anyway).

**Comment by catavallejos** [comment] 2018-10-21 21:34
All fixed now. Thank you very much for your help!

FYI, in case you are interested, there is no need for updating the `Makervars` files. All what is needed is to add:

```
SystemRequirements: C++11
NeedsCompilation: yes
```

to the `DESCRIPTION` file.

**Closed by catavallejos** 2018-10-21 21:34 UTC
Labels: enhancement
