### ISSUE TITLE
BASiCS_VarianceDecomp() problem

### ISSUE THREAD

**Issue by xuchang116** [catavallejos/BASiCS#25] opened 2018-01-10 16:08 UTC
Hello, I'm getting this error message when running BASiCS_VarianceDecomp(Chain = ChainSC ):
**no slot of name "delta" for this object of class "BASiCS_Chain"**

ChainSC is the internal chain data referred in the vignettes. I got the same error with my own data (MCMC was successful). 

I am running R 3.4.2 and BASiCS 1.0.0

Sincerely, 
Chang Xu

**Comment by catavallejos** [comment] 2018-01-30 00:31
Hi Chang Xu,

My apologies for the delayed response but I was on annual leave when you submitted this issue.

I am afraid that I was not able to reproduce the error you mentioned (I am using R 3.4.3, but that should not be relevant for the error you mentioned). Did you install BASiCS from Bioconductor or from this Github repository? I just installed BASiCS from Bioconductor and everything works fine for me. 

Here is the code I used:

```
source("https://bioconductor.org/biocLite.R")
biocLite("BASiCS")
library(BASiCS)
packageVersion("BASiCS")
[1] ‘1.0.0’
data(ChainSC)
VD <- BASiCS_VarianceDecomp(ChainSC)
```

Please let me know if this is still not working and I will look into it.

Best

Cata

**Comment by catavallejos** [comment] 2018-02-05 15:25
Closing issue. Please open is problem is unresolved.

**Closed by catavallejos** 2018-02-05 15:25 UTC
