### ISSUE TITLE
BASiCS_MCMC runtime

### ISSUE THREAD

**Issue by ndsimons** [catavallejos/BASiCS#110] opened 2019-07-22 19:29 UTC
Hi, 

I'm running BASiCS_MCMC on a dataset with ~15k cells, with no spikes. My code is pretty straightforward, taken from the tutorial: 
```
Chain <- BASiCS_MCMC(Data = DataExample, N = 20000, Thin = 20, Burn = 10000, 
                     PrintProgress = TRUE, Regression = FALSE, WithSpikes = FALSE)
```

It looks like it would take about 2 weeks to run given 128G RAM split across 12 cores on our compute cluster. 

Does this seem right? Is there anything I can do to speed this step up?

Thanks very much!
Noah

P.S. Here's my sessionInfo():
```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)

Matrix products: default
BLAS: /usr/lib64/libblas.so.3.2.1
LAPACK: /usr/lib64/liblapack.so.3.2.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] BASiCS_1.4.7                ggplot2_3.1.1              
 [3] KernSmooth_2.23-15          SingleCellExperiment_1.4.1 
 [5] SummarizedExperiment_1.12.0 DelayedArray_0.8.0         
 [7] BiocParallel_1.16.6         matrixStats_0.54.0         
 [9] Biobase_2.42.0              GenomicRanges_1.34.0       
[11] GenomeInfoDb_1.18.2         IRanges_2.16.0             
[13] S4Vectors_0.20.1            BiocGenerics_0.28.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1               locfit_1.5-9.1           lattice_0.20-38         
 [4] assertthat_0.2.1         R6_2.4.0                 plyr_1.8.4              
 [7] dynamicTreeCut_1.63-1    coda_0.19-2              pillar_1.4.0            
[10] zlibbioc_1.28.0          rlang_0.3.4              lazyeval_0.2.2          
[13] data.table_1.12.2        Matrix_1.2-15            BiocNeighbors_1.0.0     
[16] statmod_1.4.30           stringr_1.4.0            igraph_1.2.4.1          
[19] RCurl_1.95-4.12          munsell_0.5.0            HDF5Array_1.10.1        
[22] compiler_3.5.3           vipor_0.4.5              pkgconfig_2.0.2         
[25] ggbeeswarm_0.6.0         tidyselect_0.2.5         tibble_2.1.1            
[28] gridExtra_2.3            GenomeInfoDbData_1.2.0   edgeR_3.24.3            
[31] viridisLite_0.3.0        crayon_1.3.4             dplyr_0.8.1             
[34] withr_2.1.2              MASS_7.3-51.1            bitops_1.0-6            
[37] grid_3.5.3               gtable_0.3.0             magrittr_1.5            
[40] scales_1.0.0             stringi_1.4.3            XVector_0.22.0          
[43] reshape2_1.4.3           viridis_0.5.1            testthat_2.1.1          
[46] limma_3.38.3             scater_1.10.1            DelayedMatrixStats_1.4.0
[49] Rhdf5lib_1.4.3           tools_3.5.3              glue_1.3.1              
[52] beeswarm_0.2.3           purrr_0.3.2              scran_1.10.2            
[55] colorspace_1.4-1         rhdf5_2.26.2
```

**Comment by Alanocallaghan** [comment] 2019-07-22 20:21
Hi @ndsimons - how many genes does your data contain? Generally, I am not surprised at approximately that runtime. Run time scales linearly with the number of cells, and due to the inference method we use (MCMC), we can only use a single core to fit the model.

This is something we are actively working on, and we may have some solutions for you to try out - I'll get back to you as soon as I can.

PS - I would recommend running with `Regression=TRUE` as it generates estimates of variability above or below that expected based on mean expression. See [this paper](https://www.cell.com/cell-systems/fulltext/S2405-4712(18)30278-3) from last year for more detail

**Comment by catavallejos** [comment] 2019-07-22 20:34
Hi @ndsimons, thanks for getting in touch. In addition to @Alanocallaghan 's comments. Is there any population structure (e.g. distinct cell types) within the ~15K cells?

**Comment by ndsimons** [comment] 2019-07-23 01:29
Hi @Alanocallaghan and @catavallejos 

Thanks for the feedback - I'm running about 12k genes. And yes, there's strong populations structure in the data, it's PBMCs. I've also split the data out into individual cell types which are much smaller, of course, so I may have to skip doing the entire dataset and do the individual cell types separately. 

Let me know if you want me to try out any multithreading solutions on my data!

Thanks!
Noah

**Comment by catavallejos** [comment] 2019-07-26 09:37
Hi @ndsimons 

As you there is strong population structure in your date, we will strongly encourage you to split the data per cell type and run separate MCMC chains for each cell type (BASiCS assumes there is no strong population structure, so the model is not guaranteed to work otherwise). You can remove global mRNA content offsets between the populations post-hoc. 

Let us know if you have any questions! 

Best

Cata

**Comment by catavallejos** [comment] 2019-07-29 23:57
@ndsimons, I will close this issue for now but please let us know if you have any questions/issues

Best

Cata

**Closed by catavallejos** 2019-07-29 23:57 UTC

**Comment by Alanocallaghan** [comment] 2022-02-17 13:09
For posterity, we've since added functionality to BASiCS to split inference over batches of genes. The following example fits a model to toy data with 4000 genes, and then fits the same model by splitting the data into 4 batches, fitting the model on each batch, and then combining the subposteriors. See [Bardenet et al.](https://www.jmlr.org/papers/volume18/15-205/15-205.pdf) for some details on these algorithms.

```r
library("BASiCS")
library("BiocParallel")
## register the number of cores here as normal with biocparallel
## you cant use multicoreparam currently with BASiCS
register(SnowParam())

## make some mock data
sce <- BASiCS_MockSCE(NGenes = 4000, NCells = 100)

## fit a model normally
fit_joint <- BASiCS_MCMC(sce,
    ## N,Thin,Burn here are far too low, as this is just for a demonstration
    N = 2000, Thin = 10, Burn = 1000, Regression = TRUE, WithSpikes = TRUE
)

fit_split <- BASiCS_MCMC(sce,
    ## N,Thin,Burn here are far too low, as this is just for a demonstration
    N = 2000, Thin = 10, Burn = 1000, Regression = TRUE, WithSpikes = TRUE,
    ## split the data into batches with 1000 genes each
    SubsetBy = "gene", NSubsets = 4
)

BASiCS_ShowFit(fit_joint)
BASiCS_ShowFit(fit_split)
```

It's worth noting that the uncertainty in the regression coefficients is much higher, but the estimates of mean and (residual) overdispersion are pretty reliable as long as there's a good amount of genes per partition (I'd say 500 per partition is safe). We've a publication in the works that will explain this in more detail, with some positive results on model robustness.
